
/* Настройки записей онлайн */

export const recordsConfig = [
    {
        img: 'records1.webp',
        name: 'Brahms: 21 Hungarian Dances, WoO 1: No. 21 in E Minor, Vivace',
        artists: 'Metamorphose String Orchestra, Pavel Lyubomudrov',
        totalLength: 'Total length 1:19',
        spotify: 'https://open.spotify.com/album/5crQYTkRMcKspJcQwiOaXt?si=OEt_-Fx1R1edu9uG5vAz_g',
        zvuk: 'https://zvuk.com/release/31157480',
        yandex: 'https://music.yandex.ru/album/27241725',
        youtube: 'https://www.youtube.com/watch?v=E1j-zGEs33g&list=OLAK5uy_mDGVBf-QgoYti-rbM7ZuSBVWdnnY3Rdlw',
    },
    {
        img: 'records2.webp',
        name: 'Gluck: Orfeo ed Euridice, Wq. 30: "Overture"',
        artists: 'Metamorphose String Orchestra, Pavel Lyubomudrov',
        totalLength: 'Total length 3:08',
        spotify: 'https://open.spotify.com/album/4Gb4w4IP78f0oKgV9Db8n7?si=qQ1QX8d2RjSGVS56A5SGag ',
        zvuk: 'https://zvuk.com/release/31034768',
        yandex: 'https://music.yandex.ru/album/27125977 ',
        youtube: 'https://www.youtube.com/watch?v=pUuV7tseUfs&list=OLAK5uy_mXY2GFlx-PWd2faPSXgrGsE3UyMwQPbi4  ',
    },
    {
        img: 'records3.webp',
        name: 'PinocchioSuite per Orchestra d\'Archi e Mandolino',
        artists: 'Metamorphose String Orchestra, Pavel Lyubomudrov',
        totalLength: 'Total length ≈ 35:00',
        spotify: 'https://open.spotify.com/album/0A7HN2uW5SvafsRXZ4CHfo?si=VQAQ7as6RMSGmTbFK5fnzw',
        zvuk: 'https://zvuk.com/release/30768044',
        yandex: 'https://music.yandex.ru/album/26847361',
        youtube: 'https://www.youtube.com/watch?v=qH-DpGJwQYc&list=OLAK5uy_k1drZSfu33wrw0XyNfE8Mul5UuaQE8OMw',
    },
    {
        img: 'records4.webp',
        name: 'Adagio: Prayer for Peace',
        artists: 'Metamorphose String Orchestra, Pavel Lyubomudrov',
        totalLength: 'Total length 9:22',
        spotify: 'https://open.spotify.com/album/7E32dDUsF8k2XvMbhzVvk8?si=OYnsbIJwQtWkZ1wQfOP-vQ ',
        zvuk: 'https://zvuk.com/release/28389122',
        yandex: 'https://music.yandex.ru/album/24786289',
        youtube: 'https://www.youtube.com/watch?v=2LdjfIPgX_A&list=OLAK5uy_mgCCOkpMt2P5Yc5pOGq_ienOG7rcDF8Wo',
    },
    {
        img: 'records5.webp',
        name: 'Erlkönig, D. 328',
        artists: 'Metamorphose String Orchestra, Pavel Lyubomudrov',
        totalLength: 'Total length 3:38',
        spotify: 'https://open.spotify.com/album/1MwSrk6nWdl2k3yQZlpNlh?si=5ftyCDbPQiiyloNHoHohWQ ',
        zvuk: 'https://zvuk.com/release/28354669',
        yandex: 'https://music.yandex.ru/album/24745115 ',
        youtube: 'https://www.youtube.com/watch?v=E7i7kiwvjQc&list=OLAK5uy_mcZaldkOm_yXXTuXFmLMQpyYuSHENhpE4  ',
    },
    {
        img: 'records6.webp',
        name: 'Symphony No. 9, Op. 95 "From the New World": II. Largo',
        artists: 'Metamorphose String Orchestra, Pavel Lyubomudrov',
        totalLength: 'Total length 7:44',
        spotify: 'https://open.spotify.com/album/74oKmjuVSOeISNzRFWJ971?si=CIOx9YTVRHiEj_GjO9BFgg',
        zvuk: 'https://zvuk.com/release/28354645',
        yandex: 'https://music.yandex.ru/album/24745119',
        youtube: 'https://www.youtube.com/watch?v=i1nkXCxJ7Mc&list=OLAK5uy_lYt0q4hEOyErmFy5GigGPkqv1JlmJX6do',
    },
    {
        img: 'records7.webp',
        name: 'Vivaldi: Concerto alla Rustica for Strings in G Major: I. Presto',
        artists: 'Metamorphose String Orchestra, Pavel Lyubomudrov',
        totalLength: 'Total length 1:16',
        spotify: 'https://open.spotify.com/album/19VJj0sfgubLuZjqL7FfOx?si=hsUMOmoHRfa9Jehv4ad5DQ',
        zvuk: 'https://zvuk.com/release/28224911',
        yandex: 'https://music.yandex.ru/album/24624488',
        youtube: 'https://www.youtube.com/watch?v=wWJDyPWzE64&list=OLAK5uy_kvY2Ugcoo0QK-yX8KaL4MBNlhkVLR0C48',
    },
    {
        img: 'records8.webp',
        name: 'The Marriage of Figaro, K. 492: "Overture"',
        artists: 'Metamorphose String Orchestra, Pavel Lyubomudrov',
        totalLength: 'Total length 2:36',
        spotify: 'https://open.spotify.com/album/36k4MAgA7a1EGlURd6s133?si=qPTOfYPNTL2X4LiXhceeKw',
        zvuk: 'https://zvuk.com/release/28224906',
        yandex: 'https://music.yandex.ru/album/24624490',
        youtube: 'https://www.youtube.com/watch?v=m-firqwmjKI&list=OLAK5uy_mrYRKfI02B15ckjwAdTVgUuQMOrEky1t0 ',
    },
    {
        img: 'records9.webp',
        name: 'L\'Arlésienne Suite No. 2: IV. Farandole',
        artists: 'Metamorphose String Orchestra, Pavel Lyubomudrov',
        totalLength: 'Total length 3:07',
        spotify: 'https://open.spotify.com/album/6MCk7rO0YtyzEiZjG0vLzA?si=eu-JDbS0TZOThFlhUZTzHA',
        zvuk: 'https://zvuk.com/release/27150452',
        yandex: 'https://music.yandex.ru/album/23758382',
        youtube: 'https://www.youtube.com/watch?v=DK6ZEJ96oeo&list=OLAK5uy_nsAx-0rU38-9E0ylPR69RkJqvEyQ7dbqM',
    },
    {
        img: 'records10.webp',
        name: 'Elegy, Op. 58',
        artists: 'Metamorphose String Orchestra, Pavel Lyubomudrov',
        totalLength: 'Total length 4:25',
        spotify: 'https://open.spotify.com/album/3yA71f2vc8OV5ohrE4ooiq?si=eXuQjnQCRjmNbgf3rTlIUQ',
        zvuk: 'https://zvuk.com/release/27150485',
        yandex: 'https://music.yandex.ru/album/23758383',
        youtube: 'https://www.youtube.com/watch?v=niCj3oV17Ao&list=OLAK5uy_mOWBogP1Cn5cEVuIfRL9ObEFvGomZbN1I',
    },
    {
        img: 'records11.webp',
        name: 'Chanson triste',
        artists: 'Metamorphose String Orchestra, Pavel Lyubomudrov',
        totalLength: 'Total length 2:00',
        spotify: 'https://open.spotify.com/album/4KoFP3SQZhlpv9wyohdSTW?si=7xV_UR0vTiCLE3FPM3CoKA',
        zvuk: 'https://zvuk.com/release/27151583',
        yandex: 'https://music.yandex.ru/album/23756747',
        youtube: 'https://www.youtube.com/watch?v=9JuvUY_yFD0&list=OLAK5uy_nHeDRKfvz3RY_e9vl49-O6sqc_lE7kGsI',
    },
    {
        img: 'records12.webp',
        name: 'Pelléas et MélisandeSuite for String Orchestra - Live',
        artists: 'Metamorphose String Orchestra, Pavel Lyubomudrov',
        totalLength: 'Total length 36:00',
        spotify: 'https://open.spotify.com/album/3FtIduc146RcfX6FfNrRuI?si=gy8Q6_yFRCiq2F4EGPoX3g',
        zvuk: 'https://zvuk.com/release/26799246',
        yandex: 'https://music.yandex.ru/album/23673875',
        youtube: 'https://www.youtube.com/watch?v=FBmdH8Fbq5E&list=OLAK5uy_k5VqpiyzKXAPPaQdnFvIOKPs0tMGTRzPs',
    },
    {
        img: 'records13.webp',
        name: 'Marco PoloMain Theme',
        artists: 'Metamorphose String Orchestra, Pavel Lyubomudrov',
        totalLength: 'Total length 3:22',
        spotify: 'https://open.spotify.com/album/7I7QreRY8HJgztuIpfWJJl?si=MYc31Mz-QJaSAROa1AXNtg',
        zvuk: 'https://zvuk.com/release/25496789',
        yandex: 'https://music.yandex.ru/album/23304501',
        youtube: 'https://www.youtube.com/watch?v=d24Qmn6Op1U&list=OLAK5uy_n9F370Tm4DHRfmTlePGVg5L3WxPTbAJ-I',
    },
    {
        img: 'records14.webp',
        name: 'NocturneFrom "The Lady Caliph"',
        artists: 'Metamorphose String Orchestra, Pavel Lyubomudrov',
        totalLength: 'Total length 2:34',
        spotify: 'https://open.spotify.com/album/48DOU3D2TAIaozu7ObxoXl?si=F0WdoDKGRrimYs3gdVv6Ow',
        zvuk: 'https://zvuk.com/release/25496787',
        yandex: 'https://music.yandex.ru/album/23304473',
        youtube: 'https://www.youtube.com/watch?v=SDZXGqjywKA&list=OLAK5uy_lepE08sJPpGXgXp0zjondspeLHBxzNlEg',
    },
    {
        img: 'records15.webp',
        name: 'DinnerFrom "The Lady Caliph"',
        artists: 'Metamorphose String Orchestra, Pavel Lyubomudrov',
        totalLength: 'Total length 3:44',
        spotify: 'https://open.spotify.com/album/6noC6mQlu0G8oSbe1si3SM?si=Fj1KhD-nQkKFy6ppY38tfA',
        zvuk: 'https://zvuk.com/release/25496790',
        yandex: 'https://music.yandex.ru/album/23304504',
        youtube: 'https://www.youtube.com/watch?v=Y-0Gzp8_jEY&list=OLAK5uy_n6B6DkTWYmp3dnxHO8AXMTOEVN5WKs4ss',
    },
    {
        img: 'records16.webp',
        name: 'JourneyTheme from "Moses"',
        artists: 'Metamorphose String Orchestra, Pavel Lyubomudrov',
        totalLength: 'Total length 4:40',
        spotify: 'https://open.spotify.com/album/4ujaeWABFVa04QMtiC8Nnf?si=5PQqL99fRcG0SGZCMUhgvw',
        zvuk: 'https://zvuk.com/release/25496791',
        yandex: 'https://music.yandex.ru/album/23304499',
        youtube: 'https://www.youtube.com/watch?v=LYjGEbTjmZg&list=OLAK5uy_nYgU3A29KTV2DBll4jTgKpC82wsnnz73c',
    },
    {
        img: 'records17.webp',
        name: 'Sicilienne, Op. 78',
        artists: 'Metamorphose String Orchestra, Pavel Lyubomudrov',
        totalLength: 'Total length 3:39',
        spotify: 'https://open.spotify.com/album/7aHfAd1IW6yhNdJaTQoHcb?si=FIKfMTCbRyakkTjIDOCnVQ',
        zvuk: 'https://zvuk.com/release/23838887',
        yandex: 'https://music.yandex.ru/album/22343149',
        youtube: 'https://www.youtube.com/watch?v=yCAD-jdPieU&list=OLAK5uy_niQCbD6k4-YiPPukJb796vlKCwERsk5aM',
    },
    {
        img: 'records18.webp',
        name: 'Crisantemi, SC 65',
        artists: 'Metamorphose String Orchestra, Pavel Lyubomudrov',
        totalLength: 'Total length 7:31',
        spotify: 'https://open.spotify.com/album/62BxhJWQpZWT054BVhFSp0?si=YTtxvgHRTAa57_FNZG2C1A',
        zvuk: 'https://zvuk.com/release/21829390',
        yandex: 'https://music.yandex.ru/album/20838964',
        youtube: 'https://www.youtube.com/watch?v=igY-nkSRnE4&list=OLAK5uy_mWnPWNBifCIRz4jM4bajMmxyDQsYuAwBQ',
    },
    {
        img: 'records19.webp',
        name: '5 Lieder, Op. 49: No. 4, WiegenliedBrahms\'s Lullaby',
        artists: 'Metamorphose String Orchestra, Pavel Lyubomudrov',
        totalLength: 'Total length 2:07',
        spotify: 'https://open.spotify.com/album/1NLzrORbblr3rgAXw6ncZS?si=nuk2_nwtRwCeJPLu0Sbo3Q',
        zvuk: 'https://zvuk.com/release/20371265',
        yandex: 'https://music.yandex.ru/album/19236987',
        youtube: 'https://www.youtube.com/watch?v=j-1P23CgLc8&list=OLAK5uy_kkqi0RcoW_TJjuKNcnDsNscNWPWLUurxY',
    },
    {
        img: 'records20.webp',
        name: 'Serenade for Strings in E Major, Op. 22',
        artists: 'Metamorphose String Orchestra, Pavel Lyubomudrov',
        totalLength: 'Total length 31:00',
        spotify: 'https://open.spotify.com/album/7uzCaU7pRPbVxmCv6PGlli?si=tWokjBDKQMOUv-fZSaPoGg',
        zvuk: 'https://zvuk.com/release/20373323',
        yandex: 'https://music.yandex.ru/album/19000558',
        youtube: 'https://www.youtube.com/watch?v=Q88pHCpiKkI&list=OLAK5uy_ksucY2TNQEu8D_aFD6QJCtnuRuL2gUS8A',
    },
    {
        img: 'records22.webp',
        name: 'Edvard Grieg: Holberg Suite, Op.40 Live',
        artists: 'Metamorphose String Orchestra, Pavel Lyubomudrov',
        totalLength: 'Total length 19:00',
        spotify: 'https://open.spotify.com/album/7uYfZZCgltg42gQ7m79CTt?si=Bb7UI7V1TeCuyZQm53ZGug',
        zvuk: '',
        yandex: 'https://music.yandex.ru/album/13088724',
        youtube: 'https://www.youtube.com/watch?v=bHnJZO0h0Eo&list=OLAK5uy_kZM949CzRptnR4hhokla7TFMyWpfEDXfs',
    },
    {
        img: 'records23.webp',
        name: 'Ave Maria, CG 89a',
        artists: 'Metamorphose String Orchestra, Pavel Lyubomudrov',
        totalLength: 'Total length 4:43',
        spotify: 'https://open.spotify.com/album/5WRCg6RSS6SAmwGcaq5Xai?si=9p3Xv5wlTCup24hKZb82Pw',
        zvuk: '',
        yandex: 'https://music.yandex.ru/album/12020678',
        youtube: 'https://www.youtube.com/watch?v=qnIa9jtnTo8',
    },
    {
        img: 'records24.webp',
        name: 'Tchaikovsky: Souvenir de Florence, Andante Cantabile',
        artists: 'Metamorphose String Orchestra, Pavel Lyubomudrov',
        totalLength: 'Total length 10:25',
        spotify: 'https://open.spotify.com/album/5SSLgoXOyeeqqmKaFm66h3?si=zAWzLjFVS66nMCanQv__2A',
        zvuk: '',
        yandex: 'https://music.yandex.ru/album/10446752',
        youtube: 'https://www.youtube.com/watch?v=n6UXJzIUZVs&list=OLAK5uy_l_rO7XLMo3A-eXS4wHiybuwinEhr6Jl0M',
    },
    {
        img: 'records25.webp',
        name: 'Mozart: Divertimento K. 136 & K. 138 "Salzburg Symphonies"',
        artists: 'Metamorphose String Orchestra, Pavel Lyubomudrov',
        totalLength: 'Total length 17:00',
        spotify: 'https://open.spotify.com/album/5Y1l2PCzYNlFVbYWjlhv14?si=hvRQB39BSzS5N84mU0ad5A',
        zvuk: '',
        yandex: 'https://music.yandex.ru/album/6633501',
        youtube: 'https://www.youtube.com/watch?v=30e-c7btxRk&list=OLAK5uy_kDe0v36rrf0xp4fJMKSEniO11RPtiufnk',
    },
];