
/* Настройки записей онлайн */

export const recordsConfig = [
    {
        img: 'records1.png',
        name: 'А. Литвиновский. Сюита «Пеллеас и Мелизанда»',
        artists: 'Струнный оркестр «Метаморфоза», Павел Любомудров',
        ean: 'EAN 8030615140534',
        totalLength: 'Total length 37 min',
        spotify: 'https://vk.com',
        zvuk: 'https://vk.com',
        yandex: 'https://vk.com',
        apple: 'https://vk.com',
        youtube: 'https://vk.com',
    },
    {
        img: 'records2.png',
        name: 'В. А. Моцарт. Маленькая ночная серенада',
        artists: 'Струнный оркестр «Метаморфоза», Павел Любомудров',
        ean: '-',
        totalLength: 'Total length 14:19',
        spotify: 'https://vk.com',
        zvuk: 'https://vk.com',
        yandex: 'https://vk.com',
        apple: 'https://vk.com',
        youtube: 'https://vk.com',
    },
    {
        img: 'records3.png',
        name: 'А. Литвиновский. Сюита «Пеллеас и Мелизанда»',
        artists: 'Струнный оркестр «Метаморфоза», Павел Любомудров',
        ean: 'EAN 8030615140534',
        totalLength: 'Total length ≈ 13:00',
        spotify: 'https://vk.com',
        zvuk: 'https://vk.com',
        yandex: 'https://vk.com',
        apple: 'https://vk.com',
        youtube: 'https://vk.com',
    },
    {
        img: 'records4.png',
        name: 'Нино Рота: «Время для нас»',
        artists: 'Струнный оркестра «Метаморфоза», Марина Новак, Павел Любомудров',
        ean: 'EAN: /ASIN: B08NZ8BQVR',
        totalLength: 'Total length 2:59',
        spotify: 'https://vk.com',
        zvuk: 'https://vk.com',
        yandex: 'https://vk.com',
        apple: 'https://vk.com',
        youtube: 'https://vk.com',
    },
    {
        img: 'records5.png',
        name: 'Астор Пьяццолла: Аве Мария',
        artists: 'Струнный оркестра «Метаморфоза», Марина Новак, Павел Любомудров',
        ean: 'EAN: 8030615129065',
        totalLength: 'Total length 5:51',
        spotify: 'https://vk.com',
        zvuk: 'https://vk.com',
        yandex: 'https://vk.com',
        apple: 'https://vk.com',
        youtube: 'https://vk.com',
    },
    {
        img: 'records6.png',
        name: 'Людвиг ван Бетховен. Симфония № 3 «Героическая»',
        artists: 'Струнный оркестр «Метаморфоза», Павел Любомудров',
        ean: 'EAN: 8030615129157',
        totalLength: 'Total length 51:10',
        spotify: 'https://vk.com',
        zvuk: 'https://vk.com',
        yandex: 'https://vk.com',
        apple: 'https://vk.com',
        youtube: 'https://vk.com',
    },
    {
        img: 'records4.png',
        name: 'Нино Рота: «Время для нас»',
        artists: 'Струнный оркестра «Метаморфоза», Марина Новак, Павел Любомудров',
        ean: 'EAN: /ASIN: B08NZ8BQVR',
        totalLength: 'Total length 2:59',
        spotify: 'https://vk.com',
        zvuk: 'https://vk.com',
        yandex: 'https://vk.com',
        apple: 'https://vk.com',
        youtube: 'https://vk.com',
    },
    {
        img: 'records5.png',
        name: 'Астор Пьяццолла: Аве Мария',
        artists: 'Струнный оркестра «Метаморфоза», Марина Новак, Павел Любомудров',
        ean: 'EAN: 8030615129065',
        totalLength: 'Total length 5:51',
        spotify: 'https://vk.com',
        zvuk: 'https://vk.com',
        yandex: 'https://vk.com',
        apple: 'https://vk.com',
        youtube: 'https://vk.com',
    },
    {
        img: 'records6.png',
        name: 'Людвиг ван Бетховен. Симфония № 3 «Героическая»',
        artists: 'Струнный оркестр «Метаморфоза», Павел Любомудров',
        ean: 'EAN: 8030615129157',
        totalLength: 'Total length 51:10',
        spotify: 'https://vk.com',
        zvuk: 'https://vk.com',
        yandex: 'https://vk.com',
        apple: 'https://vk.com',
        youtube: 'https://vk.com',
    },
];